apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-web
  template:
    metadata:
      labels:
        app: grpc-web
    spec:
      containers:
      - name: grpc-web
        image: grpc-web-example:0.1.10
        imagePullPolicy: Never
        ports:
        - containerPort: 9074