apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maintemplate
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: flutter
          servicePort: 80
      - path: /grpc-web
        backend:
          serviceName: envoy
          servicePort: 443