apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maintemplate
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.global-static-ip-name: "maintemplate-static-ip"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: flutter
          servicePort: 80
        path: /*
      - backend:
          serviceName: envoy
          servicePort: 443
        path: /v1\.ChatService*