apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maintemplate
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: flutter
          servicePort: 80
        path: /flutter
      - backend:
          serviceName: envoy
          servicePort: 443
        path: /v1.ChatService    