apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maintemplate
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: flutter
          servicePort: 80
      - path: /v1.ChatService
        backend:
          serviceName: envoy
          servicePort: 443
      - path: /v2/*
        backend:
          serviceName: web2
          servicePort: 8080